name: Java Code Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v3.9.0
      with:
        java-version: '19'
        distribution: 'zulu'
        
    - name: Build and Test
      run: |
        ./mvnw clean install

    - name: Check Code Quality
      run: |
        ./mvn checkstyle:check
        ./mvn pmd:check
        ./mvn findbugs:check
        ./mvn javadoc:javadoc
